# Generated by Django 4.1.6 on 2023-04-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cin_number',
            field=models.IntegerField(default=0, verbose_name='cin_number'),
        ),
    ]
