# Generated by Django 4.1.6 on 2023-05-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_is_admin_remove_user_is_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cin_number',
        ),
    ]
