# Generated by Django 4.1.6 on 2023-04-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_multistepformmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultiStepFormModel',
        ),
    ]
