# Generated by Django 4.1.6 on 2023-04-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_mailmessage_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
