# Generated by Django 4.1.6 on 2023-05-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailMessage',
        ),
    ]
