# Generated by Django 4.1.6 on 2023-04-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiologist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Radiologist',
        ),
    ]
