# Generated by Django 4.1.6 on 2023-04-29 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0009_patient_notes'),
        ('radiologist', '0002_delete_radiologist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('body_part', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('abdomen', 'Abdomen'), ('pelvis', 'Pelvis'), ('extremities', 'Extremities'), ('spine', 'Spine')], max_length=100)),
                ('test_type', models.CharField(choices=[('x-ray', 'X-ray'), ('mri', 'MRI')], max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('details', models.TextField(default='', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patient')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.report')),
            ],
        ),
    ]
