# Generated by Django 4.1.6 on 2023-04-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiologist', '0004_rename_test_type_appointment_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_and_time',
            field=models.DateTimeField(),
        ),
    ]
