# Generated by Django 4.1.6 on 2023-04-30 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radiologist', '0005_alter_appointment_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='radiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiologist_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled')], default='PENDING', max_length=10),
        ),
    ]
