# Generated by Django 4.1.6 on 2023-05-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiologist', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10),
        ),
    ]
