# Generated by Django 4.1.6 on 2023-05-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_patient_notes_report'),
        ('radiologist', '0009_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.report'),
        ),
    ]
