# Generated by Django 4.1.6 on 2023-04-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
