# Generated by Django 4.1.6 on 2023-04-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_first_name_patient_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cin_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
