# Generated by Django 4.1.6 on 2023-04-12 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiologist', '0001_initial'),
        ('doctor', '0003_alter_patient_cin_number_alter_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='radiologist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='radiologist.radiologist'),
        ),
    ]
