# Generated by Django 4.1.6 on 2023-04-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='details',
        ),
    ]
