# Generated by Django 4.1.6 on 2023-04-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_remove_report_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='details',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_file',
            field=models.FileField(null=True, upload_to='reports/'),
        ),
    ]
