# Generated by Django 4.1.6 on 2023-04-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_report_details_report_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Notes',
            field=models.TextField(default='', null=True),
        ),
    ]
