# Generated by Django 4.1.6 on 2023-04-30 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0009_patient_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='radiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_radiologist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('P', 'In process'), ('V', 'Reviewed'), ('C', 'Completed')], max_length=1),
        ),
    ]
