# Generated by Django 4.1.6 on 2023-04-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiologist', '0007_delete_appointment'),
        ('doctor', '0010_alter_report_radiologist_alter_report_report_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
