# Generated by Django 4.1.6 on 2023-05-01 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0011_remove_patient_notes_delete_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Notes',
            field=models.TextField(default='', null=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exam_type', models.CharField(choices=[('x-ray', 'X-Ray'), ('mri', 'MRI')], max_length=100)),
                ('body_part', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('abdomen', 'Abdomen'), ('pelvis', 'Pelvis'), ('extremities', 'Extremities'), ('spine', 'Spine')], max_length=100)),
                ('status', models.CharField(choices=[('R', 'Requested'), ('P', 'In process'), ('V', 'Reviewed'), ('C', 'Completed')], max_length=1)),
                ('urgency', models.CharField(choices=[('U', 'Urgent'), ('N', 'Normal'), ('L', 'Low')], max_length=1)),
                ('details', models.TextField(default='', null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patient')),
                ('radiologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_radiologist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
