# Generated by Django 4.1.6 on 2023-05-23 22:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_alter_report_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
